blank_issues_enabled: false
contact_links:
  - name: E‑poštna podpora / Email support
    url: mailto:svetovanje@optima-prevent.eu
    about: "SL / EN – Pišite nam, če nimate GitHub računa ali potrebujete pomoč. / Write us if you do not have a GitHub account or need help."